apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "configstream.fullname" . }}
  labels:
    {{- include "configstream.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "configstream.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "configstream.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        {{- if .Values.prometheus.enabled }}
        - name: metrics
          containerPort: {{ .Values.prometheus.port }}
          protocol: TCP
        {{- end }}
        env:
        - name: CONFIGSTREAM_INTERVAL
          value: "{{ .Values.config.testInterval }}"
        - name: CONFIGSTREAM_PORT
          value: "8080"
        volumeMounts:
        - name: data
          mountPath: /app/data
        - name: config
          mountPath: /app/config
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: data
        {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ include "configstream.fullname" . }}-data
        {{- else }}
        emptyDir: {}
        {{- end }}
      - name: config
        configMap:
          name: {{ include "configstream.fullname" . }}-config