version: '3.8'
services:
  vpn_merger:
    build: .
    image: vpn-merger
    volumes:
      - ./output:/app/output
    command: >
      sh -c "while true; do \
                python vpn_merger.py && echo 'Waiting for next run'; \
                sleep ${MERGE_INTERVAL:-86400}; \
             done"
    environment:
      - MERGE_INTERVAL=86400
