version: '3.8'

services:
  configstream:
    build: .
    container_name: configstream
    ports:
      - "8080:8080"
      - "9090:9090"
    volumes:
      - ./data:/app/data
      - ./config:/app/config
    environment:
      - CONFIGSTREAM_INTERVAL=2
      - CONFIGSTREAM_PORT=8080
    restart: unless-stopped
    healthcheck:
      test:
        - "CMD-SHELL"
        - >
          python - <<'PY' || exit 1
          import sys, urllib.request
          try:
              with urllib.request.urlopen('http://localhost:8080/api/statistics', timeout=5) as r:
                  sys.exit(0 if r.status == 200 else 1)
          except Exception:
              sys.exit(1)
          PY
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9091:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: unless-stopped

volumes:
  prometheus_data:
  grafana_data: