[project]
name = "massconfigmerger"
version = "0.1.0"
description = "Tools for aggregating and merging VPN configuration links"
authors = [{name = "Amirreza Farnam Taheri"}]
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "aiohttp",
    "aiodns",
    "nest-asyncio",
    "telethon",
    "PyYAML",
    "geoip2",
]

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"
