replicaCount: 1

image:
  repository: configstream
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 8080
  metricsPort: 9090

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: configstream.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

persistence:
  enabled: true
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 5Gi

config:
  testInterval: 2
  maxConcurrentTests: 50
  testTimeout: 5
  enableAdvancedTests: false
  maxPingMs: 1000
  excludeBlocked: true

sources: []
  # - https://raw.githubusercontent.com/example/vpn/main/configs.txt

prometheus:
  enabled: true
  port: 9090