apiVersion: apps/v1
kind: Deployment
metadata:
  name: configstream
  labels:
    app: configstream
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configstream
  template:
    metadata:
      labels:
        app: configstream
    spec:
      containers:
      - name: configstream
        image: configstream:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        - name: metrics
          containerPort: 9090
          protocol: TCP
        env:
        - name: CONFIGSTREAM_INTERVAL
          value: "2"
        - name: CONFIGSTREAM_PORT
          value: "8080"
        volumeMounts:
        - name: data
          mountPath: /app/data
        - name: config
          mountPath: /app/config
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/statistics
            port: http
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /api/statistics
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: configstream-data
      - name: config
        configMap:
          name: configstream-config