theme: jekyll-theme-cayman
title: ConfigStream
description: Advanced VPN Configuration Aggregator & Monitoring System
baseurl: ""
url: "https://amirrezafarnamtaheri.github.io/configStream/"

# Author information
author:
  name: "Amirreza 'Farnam' Taheri"
  email: "taherifarnam@gmail.com"

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    default_lang: python

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

# Collections
collections:
  documentation:
    output: true
    permalink: /docs/:path/

# Navigation
navigation:
  - title: Home
    url: /
  - title: Web Interface
    url: /web-interface/
  - title: Getting Started
    url: /getting-started/
  - title: Configuration
    url: /configuration/
  - title: Advanced Troubleshooting
    url: /advanced-troubleshooting/
  - title: API Reference
    url: /api/
  - title: GitHub
    url: https://github.com/AmirrezaFarnamTaheri/ConfigStream/

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .github