theme: jekyll-theme-cayman
title: ConfigStream
description: Advanced VPN Configuration Aggregator & Monitoring System
baseurl: ""
url: "https://yourusername.github.io/configstream"

# Author information
author:
  name: Your Name
  email: your.email@example.com

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    default_lang: python

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

# Collections
collections:
  documentation:
    output: true
    permalink: /docs/:path/

# Navigation
navigation:
  - title: Home
    url: /
  - title: Getting Started
    url: /getting-started/
  - title: API Reference
    url: /api/
  - title: Examples
    url: /examples/
  - title: GitHub
    url: https://github.com/yourusername/configstream

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .github