theme: jekyll-theme-cayman
title: ConfigStream
description: Advanced VPN Configuration Aggregator & Monitor
baseurl: "/configstream"
url: "https://yourusername.github.io"

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

author: Amirreza 'Farnam' Taheri
email: taherifarnam@gmail.com
url: https://amirrezafarnamtaheri.github.io/configStream/