name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: requirements.txt
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install flake8 mypy types-PyYAML
      - name: Run tests
        run: pytest -q
      - name: Run flake8
        run: flake8 .
      - name: Run mypy
        run: mypy .
