name: Daily Update

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: requirements.txt
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run aggregator tool
        run: python src/configstream/aggregator_tool.py --with-merger --hours 24
      - name: Set timestamp
        id: timestamp
        run: echo "time=$(date -u '+%Y-%m-%d %H:%M:%S UTC')" >> "$GITHUB_OUTPUT"
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "feat: Auto-update subscription files [${{ steps.timestamp.outputs.time }}]"
          file_pattern: output/**
